import Head from 'next/head';
import '@/styles/global.css';

export const metadata = {
  title: 'Бургер Чеддер',
  description: 'Generated by Next.js',
};

import Nav from "@/components/Nav/Nav"


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
